### ISSUE TITLE
FParsec was not available (from Nuget).

### ISSUE THREAD

**Issue by tokemath** [stephan-tolksdorf/fparsec#50]
I tried to get FParsec from Nuget, but it failed. I will be happy when it becomes available.

> NuGet Error NU1108
> A circular dependency was detected.
> The package is authored incorrectly; contact the package owner to correct the bug.

Excuse me, I'm not used to English and GitHub.

**Comment by FoggyFinder** [comment]
I doubt there is a problem with FParsec itself.

What is a name of your Project? What is a name of the folder that contains the project?

If it is something like `FParsec` I suggest you renaming the project since description that you provided sounds similar to known issue:

https://github.com/NuGet/Home/issues/6754

**Comment by tokemath** [comment]
The problem has been solved completely.
I thank you and apologize for my mistakes.
thank you very much!
